# Generated by Django 3.0.2 on 2020-01-08 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('gasto_fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('numero_factura', models.CharField(blank=True, max_length=200)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
